In [7]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [45]:
raw_df = pd.read_csv(
    "Melbourne01.csv",     
    header=None,           
    dtype=str, 
    on_bad_lines="skip",   
    skipinitialspace=True  
)

raw_df.head(10)

     0  1  2  3   4     5    6     7   8    9   10  11      12   13
0  2011  1  1  0   4  24.8  0.0  14.0  51   SE  11  13  1007.4  0.0
1  2011  1  1  0   4  24.8  0.0  14.0  51   SE  11  13  1007.4  0.0
2  2011  1  1  0  14  24.8  0.0  13.3  48   SE  11  11  1007.5  0.0
3  2011  1  1  0  14  24.8  0.0  13.3  48   SE  11  11  1007.5  0.0
4  2011  1  1  0  24  24.9  0.0  13.3  48   SE  11  13  1007.5  0.0
5  2011  1  1  0  24  24.9  0.0  13.3  48   SE  11  13  1007.5  0.0
6  2011  1  1  0  34  24.7  0.0  13.4  49   SE  11  11  1007.4  0.0
7  2011  1  1  0  34  24.7  0.0  13.4  49   SE  11  11  1007.4  0.0
8  2011  1  1  0  34  24.7  0.0  13.4  49   SE  11  11  1007.4  0.0
9  2011  1  1  0  44  24.1  0.0  13.3  51  ESE   9   9  1007.3  0.0

In [51]:
raw_df.shape
raw_df.columns = [
    "Year","Month","Day","Hour","Minute","Temperature","Rainfall","DewPoint","Humidity","WindDirection","WindSpeed","WindGust","Pressure","Cloud"]

raw_df.head()

,Year,Month,Day,Hour,Minute,Temperature,Rainfall,DewPoint,Humidity,WindDirection,WindSpeed,WindGust,Pressure,Cloud
0,2011,1,1,0,4,24.8,0.0,14.0,51,SE,11,13,1007.4,0.0
1,2011,1,1,0,4,24.8,0.0,14.0,51,SE,11,13,1007.4,0.0
2,2011,1,1,0,14,24.8,0.0,13.3,48,SE,11,11,1007.5,0.0
3,2011,1,1,0,14,24.8,0.0,13.3,48,SE,11,11,1007.5,0.0
4,2011,1,1,0,24,24.9,0.0,13.3,48,SE,11,13,1007.5,0.0

In [53]:
raw_df.dtypes

Year             object
Month            object
Day              object
Hour             object
Minute           object
Temperature      object
Rainfall         object
DewPoint         object
Humidity         object
WindDirection    object
WindSpeed        object
WindGust         object
Pressure         object
Cloud            object
dtype: object

In [57]:
for col in raw_df.columns:
    raw_df[col] = raw_df[col].astype(str).str.strip()
raw_df.head()

,Year,Month,Day,Hour,Minute,Temperature,Rainfall,DewPoint,Humidity,WindDirection,WindSpeed,WindGust,Pressure,Cloud
0,2011,1,1,0,4,24.8,0.0,14.0,51,SE,11,13,1007.4,0.0
1,2011,1,1,0,4,24.8,0.0,14.0,51,SE,11,13,1007.4,0.0
2,2011,1,1,0,14,24.8,0.0,13.3,48,SE,11,11,1007.5,0.0
3,2011,1,1,0,14,24.8,0.0,13.3,48,SE,11,11,1007.5,0.0
4,2011,1,1,0,24,24.9,0.0,13.3,48,SE,11,13,1007.5,0.0

In [59]:
raw_df.duplicated().sum()

537197

In [61]:
raw_df = raw_df.drop_duplicates()
raw_df.shape

(575955, 14)

In [67]:
raw_df.isna().sum()

Year             0
Month            0
Day              0
Hour             0
Minute           0
Temperature      0
Rainfall         0
DewPoint         0
Humidity         0
WindDirection    0
WindSpeed        0
WindGust         0
Pressure         0
Cloud            0
dtype: int64

In [71]:
raw_df = raw_df.dropna(subset=["Month", "Day", "Hour", "Minute"])
raw_df.isna().sum()

Year             0
Month            0
Day              0
Hour             0
Minute           0
Temperature      0
Rainfall         0
DewPoint         0
Humidity         0
WindDirection    0
WindSpeed        0
WindGust         0
Pressure         0
Cloud            0
dtype: int64

In [73]:
numeric_cols = [
    "Year",
    "Month",
    "Day",
    "Hour",
    "Minute",
    "Temperature",
    "Rainfall",
    "DewPoint",
    "Humidity",
    "WindSpeed",
    "WindGust",
    "Pressure",
    "Cloud"
]

for col in numeric_cols:
    raw_df[col] = pd.to_numeric(raw_df[col], errors="coerce")

raw_df.dtypes

Year             float64
Month            float64
Day              float64
Hour             float64
Minute           float64
Temperature      float64
Rainfall         float64
DewPoint         float64
Humidity         float64
WindDirection     object
WindSpeed        float64
WindGust         float64
Pressure         float64
Cloud            float64
dtype: object

In [75]:
raw_df["WindDirection"].unique()

array(['SE', 'ESE', 'NE', 'NNE', 'ENE', 'W', 'N', 'SW', 'SSE', 'S', 'SSW',
       'WSW', 'NW', 'WNW', 'NNW', 'E', 'CALM', '1016.6', '1016.9',
       '1017.0', '1017.4', '1026.0', '1026.1', '1025.3', '1024.2',
       '1029.6', '1003.3', '1008.2', '1019.0', 'nan', '1015.5', '1014.2',
       '1015.9', '1016.2', '1016.1', '1014.1', '1014.0', '1013.6',
       '1012.7', '1013.1', '1014.4', '1014.6', '1015.6', '1015.8',
       '1016.7', '1017.2', '1016.0', '1017.8', '1019.5', '1019.8',
       '1019.9', '1020.4', '1021.0', '1021.2', '1021.7', '1021.9',
       '1022.3', '1022.7', '1004.5', '1022.0', '1010.3', '1012.0',
       '1010.8', '-'], dtype=object)

In [79]:
(raw_df[["Rainfall", "WindSpeed", "WindGust", "Pressure"]] == -9999).sum()

Rainfall      1
WindSpeed     6
WindGust     10
Pressure     34
dtype: int64

In [81]:
raw_df.loc[raw_df["Rainfall"] == -9999, "Rainfall"] = np.nan
raw_df.loc[raw_df["WindSpeed"] == -9999, "WindSpeed"] = np.nan
raw_df.loc[raw_df["WindGust"] == -9999, "WindGust"] = np.nan
raw_df.loc[raw_df["Pressure"] == -9999, "Pressure"] = np.nan

raw_df[["Rainfall", "WindSpeed", "WindGust", "Pressure"]].describe()

            Rainfall      WindSpeed       WindGust       Pressure
count  575322.000000  575317.000000  575313.000000  575289.000000
mean       12.260473      19.296332      22.754826    1017.105840
std         7.080255      10.547169      12.771755      12.594023
min        -4.100000       0.000000       0.000000       0.000000
25%         7.800000      11.000000      13.000000    1012.200000
50%        11.900000      17.000000      20.000000    1017.300000
75%        16.700000      26.000000      30.000000    1022.400000
max        43.300000     100.000000     109.000000    1041.900000

In [83]:
raw_df = raw_df.assign(
    DateTime = pd.to_datetime(
        raw_df[["Year", "Month", "Day", "Hour", "Minute"]]
    )
)

raw_df.head()

,Year,Month,Day,Hour,Minute,Temperature,Rainfall,DewPoint,Humidity,WindDirection,WindSpeed,WindGust,Pressure,Cloud,DateTime
0,2011.0,1.0,1.0,0.0,4.0,24.8,0.0,14.0,51.0,SE,11.0,13.0,1007.4,0.0,2011-01-01 00:04:00
2,2011.0,1.0,1.0,0.0,14.0,24.8,0.0,13.3,48.0,SE,11.0,11.0,1007.5,0.0,2011-01-01 00:14:00
4,2011.0,1.0,1.0,0.0,24.0,24.9,0.0,13.3,48.0,SE,11.0,13.0,1007.5,0.0,2011-01-01 00:24:00
6,2011.0,1.0,1.0,0.0,34.0,24.7,0.0,13.4,49.0,SE,11.0,11.0,1007.4,0.0,2011-01-01 00:34:00
9,2011.0,1.0,1.0,0.0,44.0,24.1,0.0,13.3,51.0,ESE,9.0,9.0,1007.3,0.0,2011-01-01 00:44:00

In [85]:
cleaned_df = raw_df.assign(
    WindDirection = raw_df["WindDirection"].astype("category")
)

cleaned_df.dtypes

Year                    float64
Month                   float64
Day                     float64
Hour                    float64
Minute                  float64
Temperature             float64
Rainfall                float64
DewPoint                float64
Humidity                float64
WindDirection          category
WindSpeed               float64
WindGust                float64
Pressure                float64
Cloud                   float64
DateTime         datetime64[ns]
dtype: object

In [87]:
cleaned_df.to_csv("Melbourne01_cleaned.csv", index=False)